services:
  emonotes:
    build: .
    container_name: emonotes_backend
    env_file: .env
    ports:
      - 8080:8080
    depends_on:
      - postgres
    restart: always

  frontend:
    build: frontend/
    container_name: emonotes_frontend
    ports:
      - "80:80"
    restart: always

  postgres:
    image: postgres:16
    container_name: emonotes_postgres
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: